// backend - prisma/doctorsData.js
export default {
  doctors: [
    {
      name: 'Dr. Ayesha Rahman',
      specialty: 'Cardiologist',
      image: 'https://i.ibb.co/doctor-demo1.jpg',
      experience: '12 years',
      availability: ['09:00 AM - 12:00 PM', '05:00 PM - 08:00 PM'],
      description:
        'Highly experienced cardiologist specializing in heart diseases, preventive care, and patient-centered treatment.',
      hospital: 'Labaid Cardiac Hospital',
      location: 'Dhanmondi, Dhaka',
      fee: 1000,
    },
    {
      name: 'Dr. Rahim Ahmed',
      specialty: 'Dermatologist',
      image: 'https://i.ibb.co/doctor-demo2.jpg',
      experience: '9 years',
      availability: ['10:00 AM - 11:00 PM', '06:00 PM - 08:00 PM'],
      description:
        'Expert dermatologist with 8+ years of experience treating skin conditions, allergies, and cosmetic dermatology.',
      hospital: 'Square Hospital',
      location: 'Gulshan, Dhaka',
      fee: 700,
    },
    {
      name: 'Dr. Fatima Khan',
      specialty: 'Neurologist',
      image: 'https://i.ibb.co/doctor-demo3.jpg',
      experience: '15 years',
      availability: ['08:00 AM - 12:00 PM', '06:00 PM - 09:00 PM'],
      description:
        'Board-certified neurologist specializing in brain disorders, stroke management, and neurodegenerative diseases.',
      hospital: 'Apollo Hospital',
      location: 'Banani, Dhaka',
      fee: 1200,
    },
    {
      name: 'Dr. Kamal Islam',
      specialty: 'Orthopedic',
      image: 'https://i.ibb.co/doctor-demo4.jpg',
      experience: '17 years',
      availability: ['10:00 AM - 13:00 PM', '04:00 PM - 08:00 PM'],
      description:
        'Skilled orthopedic surgeon with expertise in joint replacement, sports injuries, and spinal surgery.',
      hospital: 'United Hospital',
      location: 'Mirpur, Dhaka',
      fee: 800,
    },
    {
      name: 'Dr. Nusrat Hossain',
      specialty: 'Pediatrician',
      image: 'https://i.ibb.co/doctor-demo5.jpg',
      experience: '18 years',
      availability: ['10:00 AM - 13:00 PM', '05:00 PM - 08:00 PM'],
      description:
        'Compassionate pediatrician dedicated to child health, developmental disorders, and preventive care.',
      hospital: 'Bangladesh Medical College Hospital',
      location: 'Uttara, Dhaka',
      fee: 700,
    },
    {
      name: 'Dr. Tanvir Chowdhury',
      specialty: 'Psychiatrist',
      image: 'https://i.ibb.co/doctor-demo6.jpg',
      experience: '22 years',
      availability: ['08:00 AM - 12:00 PM', '04:00 PM - 09:00 PM'],
      description:
        'Licensed psychiatrist providing mental health care, therapy, and medication management for various conditions.',
      hospital: 'Ibn Sina Hospital',
      location: 'Mohammadpur, Dhaka',
      fee: 1200,
    },
    {
      name: 'Dr. Sadia Ali',
      specialty: 'General Physician',
      image: 'https://i.ibb.co/doctor-demo7.jpg',
      experience: '25 years',
      availability: ['10:00 AM - 13:00 PM', '06:00 PM - 07:00 PM'],
      description:
        'General physician with broad medical knowledge, offering comprehensive primary care and health screenings.',
      hospital: 'Popular Diagnostic Center',
      location: 'Shyamoli, Dhaka',
      fee: 1200,
    },
    {
      name: 'Dr. Imran Siddiqui',
      specialty: 'Dentist',
      image: 'https://i.ibb.co/doctor-demo8.jpg',
      experience: '6 years',
      availability: ['08:00 AM - 13:00 PM', '06:00 PM - 09:00 PM'],
      description:
        'Experienced dentist specializing in cosmetic dentistry, orthodontics, and oral surgery.',
      hospital: 'Green Life Hospital',
      location: 'Farmgate, Dhaka',
      fee: 800,
    },
    {
      name: 'Dr. Rina Akter',
      specialty: 'Gynecologist',
      image: 'https://i.ibb.co/doctor-demo9.jpg',
      experience: '24 years',
      availability: ['08:00 AM - 13:00 PM', '04:00 PM - 07:00 PM'],
      description:
        "Renowned gynecologist providing women's health services, prenatal care, and reproductive health.",
      hospital: 'Holy Family Red Crescent Hospital',
      location: 'Tejgaon, Dhaka',
      fee: 1500,
    },
    {
      name: 'Dr. Shahid Hasan',
      specialty: 'ENT Specialist',
      image: 'https://i.ibb.co/doctor-demo10.jpg',
      experience: '14 years',
      availability: ['10:00 AM - 13:00 PM', '05:00 PM - 09:00 PM'],
      description:
        'ENT specialist treating ear, nose, and throat conditions with advanced diagnostic techniques.',
      hospital: 'Birdem General Hospital',
      location: 'Motijheel, Dhaka',
      fee: 800,
    },
    {
      name: 'Dr. Maliha Begum',
      specialty: 'Urologist',
      image: 'https://i.ibb.co/doctor-demo11.jpg',
      experience: '9 years',
      availability: ['10:00 AM - 11:00 PM', '04:00 PM - 07:00 PM'],
      description:
        'Urologist specializing in kidney stones, prostate health, and urinary tract disorders.',
      hospital: 'CMH Dhaka',
      location: 'Paltan, Dhaka',
      fee: 300,
    },
    {
      name: 'Dr. Arif Uddin',
      specialty: 'Oncologist',
      image: 'https://i.ibb.co/doctor-demo12.jpg',
      experience: '24 years',
      availability: ['08:00 AM - 11:00 PM', '04:00 PM - 08:00 PM'],
      description:
        'Oncologist dedicated to cancer diagnosis, chemotherapy, and personalized treatment plans.',
      hospital: 'Evercare Hospital',
      location: 'Khilgaon, Dhaka',
      fee: 1500,
    },
    {
      name: 'Dr. Tasnim Khatun',
      specialty: 'Nephrologist',
      image: 'https://i.ibb.co/doctor-demo13.jpg',
      experience: '20 years',
      availability: ['08:00 AM - 12:00 PM', '06:00 PM - 08:00 PM'],
      description:
        'Nephrologist with expertise in kidney disease, dialysis, and transplant medicine.',
      hospital: 'BRB Hospital',
      location: 'Badda, Dhaka',
      fee: 1200,
    },
    {
      name: 'Dr. Hasan Miah',
      specialty: 'Pulmonologist',
      image: 'https://i.ibb.co/doctor-demo14.jpg',
      experience: '12 years',
      availability: ['08:00 AM - 12:00 PM', '06:00 PM - 08:00 PM'],
      description:
        'Pulmonologist treating respiratory diseases, asthma, COPD, and sleep disorders.',
      hospital: 'Khidmah Hospital',
      location: 'Rampura, Dhaka',
      fee: 500,
    },
    {
      name: 'Dr. Sabina Talukder',
      specialty: 'Endocrinologist',
      image: 'https://i.ibb.co/doctor-demo15.jpg',
      experience: '24 years',
      availability: ['10:00 AM - 13:00 PM', '04:00 PM - 08:00 PM'],
      description:
        'Endocrinologist managing diabetes, thyroid disorders, and hormonal imbalances.',
      hospital: 'City Hospital',
      location: 'Malibagh, Dhaka',
      fee: 1500,
    },
    {
      name: 'Dr. Javed Barua',
      specialty: 'Gastroenterologist',
      image: 'https://i.ibb.co/doctor-demo16.jpg',
      experience: '3 years',
      availability: ['10:00 AM - 11:00 PM', '06:00 PM - 09:00 PM'],
      description:
        'Gastroenterologist specializing in digestive disorders, liver disease, and endoscopic procedures.',
      hospital: 'Central Hospital',
      location: 'Jatrabari, Dhaka',
      fee: 600,
    },
    {
      name: 'Dr. Rumana Sarker',
      specialty: 'Ophthalmologist',
      image: 'https://i.ibb.co/doctor-demo17.jpg',
      experience: '7 years',
      availability: ['09:00 AM - 12:00 PM', '04:00 PM - 09:00 PM'],
      description:
        'Ophthalmologist providing eye care, cataract surgery, and vision correction treatments.',
      hospital: 'Monowara Hospital',
      location: 'Chawkbazar, Dhaka',
      fee: 800,
    },
    {
      name: 'Dr. Faisal Das',
      specialty: 'Rheumatologist',
      image: 'https://i.ibb.co/doctor-demo18.jpg',
      experience: '10 years',
      availability: ['10:00 AM - 12:00 PM', '06:00 PM - 07:00 PM'],
      description:
        'Rheumatologist treating autoimmune diseases, arthritis, and connective tissue disorders.',
      hospital: 'Al-Rajhi Hospital',
      location: 'Savar, Dhaka',
      fee: 600,
    },
    {
      name: 'Dr. Lubna Paul',
      specialty: 'Hematologist',
      image: 'https://i.ibb.co/doctor-demo19.jpg',
      experience: '21 years',
      availability: ['10:00 AM - 13:00 PM', '06:00 PM - 07:00 PM'],
      description:
        'Hematologist specializing in blood disorders, anemia, and clotting conditions.',
      hospital: 'Ispahani Islamia Eye Hospital',
      location: 'Keraniganj, Dhaka',
      fee: 1000,
    },
    {
      name: 'Dr. Sohail Roy',
      specialty: 'Radiologist',
      image: 'https://i.ibb.co/doctor-demo20.jpg',
      experience: '9 years',
      availability: ['09:00 AM - 12:00 PM', '06:00 PM - 08:00 PM'],
      description:
        'Radiologist with expertise in medical imaging, MRI, CT scans, and diagnostic radiology.',
      hospital: 'National Institute of Cancer Research',
      location: 'Siddheswari, Dhaka',
      fee: 1000,
    },
    {
      name: 'Dr. Nazia Biswas',
      specialty: 'Cardiologist',
      image: 'https://i.ibb.co/doctor-demo21.jpg',
      experience: '10 years',
      availability: ['10:00 AM - 12:00 PM', '04:00 PM - 09:00 PM'],
      description:
        'Highly experienced cardiologist specializing in heart diseases, preventive care, and patient-centered treatment.',
      hospital: 'Labaid Cardiac Hospital',
      location: 'Dhanmondi, Dhaka',
      fee: 400,
    },
    {
      name: 'Dr. Rafiq Nath',
      specialty: 'Dermatologist',
      image: 'https://i.ibb.co/doctor-demo22.jpg',
      experience: '16 years',
      availability: ['08:00 AM - 13:00 PM', '05:00 PM - 08:00 PM'],
      description:
        'Expert dermatologist with 8+ years of experience treating skin conditions, allergies, and cosmetic dermatology.',
      hospital: 'Square Hospital',
      location: 'Gulshan, Dhaka',
      fee: 1500,
    },
    {
      name: 'Dr. Parveen Mazumder',
      specialty: 'Neurologist',
      image: 'https://i.ibb.co/doctor-demo23.jpg',
      experience: '20 years',
      availability: ['10:00 AM - 12:00 PM', '06:00 PM - 07:00 PM'],
      description:
        'Board-certified neurologist specializing in brain disorders, stroke management, and neurodegenerative diseases.',
      hospital: 'Apollo Hospital',
      location: 'Banani, Dhaka',
      fee: 900,
    },
    {
      name: 'Dr. Asif Hoque',
      specialty: 'Orthopedic',
      image: 'https://i.ibb.co/doctor-demo24.jpg',
      experience: '6 years',
      availability: ['09:00 AM - 11:00 PM', '04:00 PM - 09:00 PM'],
      description:
        'Skilled orthopedic surgeon with expertise in joint replacement, sports injuries, and spinal surgery.',
      hospital: 'United Hospital',
      location: 'Mirpur, Dhaka',
      fee: 700,
    },
    {
      name: 'Dr. Shireen Chakraborty',
      specialty: 'Pediatrician',
      image: 'https://i.ibb.co/doctor-demo25.jpg',
      experience: '20 years',
      availability: ['08:00 AM - 11:00 PM', '05:00 PM - 09:00 PM'],
      description:
        'Compassionate pediatrician dedicated to child health, developmental disorders, and preventive care.',
      hospital: 'Bangladesh Medical College Hospital',
      location: 'Uttara, Dhaka',
      fee: 1500,
    },
    {
      name: 'Dr. Mamun Dey',
      specialty: 'Psychiatrist',
      image: 'https://i.ibb.co/doctor-demo26.jpg',
      experience: '22 years',
      availability: ['09:00 AM - 11:00 PM', '06:00 PM - 09:00 PM'],
      description:
        'Licensed psychiatrist providing mental health care, therapy, and medication management for various conditions.',
      hospital: 'Ibn Sina Hospital',
      location: 'Mohammadpur, Dhaka',
      fee: 1200,
    },
    {
      name: 'Dr. Farzana Ghosh',
      specialty: 'General Physician',
      image: 'https://i.ibb.co/doctor-demo27.jpg',
      experience: '24 years',
      availability: ['10:00 AM - 13:00 PM', '06:00 PM - 08:00 PM'],
      description:
        'General physician with broad medical knowledge, offering comprehensive primary care and health screenings.',
      hospital: 'Popular Diagnostic Center',
      location: 'Shyamoli, Dhaka',
      fee: 300,
    },
    {
      name: 'Dr. Iqbal Sen',
      specialty: 'Dentist',
      image: 'https://i.ibb.co/doctor-demo28.jpg',
      experience: '15 years',
      availability: ['09:00 AM - 12:00 PM', '04:00 PM - 09:00 PM'],
      description:
        'Experienced dentist specializing in cosmetic dentistry, orthodontics, and oral surgery.',
      hospital: 'Green Life Hospital',
      location: 'Farmgate, Dhaka',
      fee: 800,
    },
    {
      name: 'Dr. Habiba Gupta',
      specialty: 'Gynecologist',
      image: 'https://i.ibb.co/doctor-demo29.jpg',
      experience: '22 years',
      availability: ['08:00 AM - 13:00 PM', '05:00 PM - 07:00 PM'],
      description:
        "Renowned gynecologist providing women's health services, prenatal care, and reproductive health.",
      hospital: 'Holy Family Red Crescent Hospital',
      location: 'Tejgaon, Dhaka',
      fee: 600,
    },
    {
      name: 'Dr. Tariq Bhowmik',
      specialty: 'ENT Specialist',
      image: 'https://i.ibb.co/doctor-demo30.jpg',
      experience: '8 years',
      availability: ['08:00 AM - 13:00 PM', '06:00 PM - 07:00 PM'],
      description:
        'ENT specialist treating ear, nose, and throat conditions with advanced diagnostic techniques.',
      hospital: 'Birdem General Hospital',
      location: 'Motijheel, Dhaka',
      fee: 1500,
    },
  ],
};
